-- MySQL Script generated by MySQL Workbench
-- Sat Nov 14 16:23:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema parquesnaturalesdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema parquesnaturalesdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parquesnaturalesdb` DEFAULT CHARACTER SET utf8 ;
USE `parquesnaturalesdb` ;

-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT 'null',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`PERSONA` (
  `id_persona` BIGINT NOT NULL,
  `nombre_persona` VARCHAR(45) NOT NULL,
  `email_persona` VARCHAR(100) NULL,
  `direccion_residencia` VARCHAR(60) NOT NULL,
  `telefono_fijo` INT NULL,
  `telefono_movil` INT NOT NULL,
  `id_usuario` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_persona`),
  INDEX `fk_PERSONA_USUARIO_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_PERSONA_USUARIO`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `parquesnaturalesdb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`ROL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`ROL` (
  `id_rol` INT NOT NULL,
  `nombre_rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`CARGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`CARGO` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `nombre_cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`DECRETO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`DECRETO` (
  `num_decreto` INT NOT NULL,
  `fecha_decreto` DATE NOT NULL,
  PRIMARY KEY (`num_decreto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`CAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`CAR` (
  `nit_CAR` BIGINT(20) NOT NULL,
  `nombre_CAR` VARCHAR(45) NOT NULL,
  `ubicacion_CAR` VARCHAR(100) NOT NULL,
  `estado_CAR` TINYINT NOT NULL DEFAULT 1,
  `DECRETO_num_decreto` INT NOT NULL,
  PRIMARY KEY (`nit_CAR`),
  INDEX `fk_CAR_DECRETO1_idx` (`DECRETO_num_decreto` ASC) VISIBLE,
  CONSTRAINT `fk_CAR_DECRETO1`
    FOREIGN KEY (`DECRETO_num_decreto`)
    REFERENCES `parquesnaturalesdb`.`DECRETO` (`num_decreto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`ESPECIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`ESPECIES` (
  `id_num_especies` INT NOT NULL,
  `num_especies_vegetales` INT NOT NULL DEFAULT 0,
  `num_especies_animales` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_num_especies`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`VALOR_INGRESO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`VALOR_INGRESO` (
  `id_valor_ingreso` INT NOT NULL,
  `valor_adultos` INT NOT NULL,
  `valor_niños` INT NOT NULL,
  PRIMARY KEY (`id_valor_ingreso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`PARQUE_NATURAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`PARQUE_NATURAL` (
  `id_parque` INT NOT NULL AUTO_INCREMENT,
  `nombre_parque` VARCHAR(100) NOT NULL,
  `extension_parque` FLOAT NULL,
  `altitud_parque` INT NULL,
  `temperatura_parque` FLOAT NULL,
  `estado_parque` TINYINT NOT NULL DEFAULT 1,
  `comunidades_indigenas` TINYINT NULL,
  `ubicacion_parque` VARCHAR(100) NOT NULL,
  `abierto_publico` TINYINT NOT NULL DEFAULT 1,
  `servicio_auditorio` TINYINT NOT NULL DEFAULT 0,
  `CAR_id_CAR` BIGINT NOT NULL,
  `ESPECIES_id_num_especies` INT NOT NULL,
  `DECRETO_num_decreto` INT NOT NULL,
  `VALOR_INGRESO_id_valor_ingreso` INT NOT NULL,
  PRIMARY KEY (`id_parque`),
  INDEX `fk_PARQUE_NATURAL_CAR1_idx` (`CAR_id_CAR` ASC) VISIBLE,
  INDEX `fk_PARQUE_NATURAL_ESPECIES1_idx` (`ESPECIES_id_num_especies` ASC) VISIBLE,
  INDEX `fk_PARQUE_NATURAL_DECRETO1_idx` (`DECRETO_num_decreto` ASC) VISIBLE,
  INDEX `fk_PARQUE_NATURAL_VALOR_INGRESO1_idx` (`VALOR_INGRESO_id_valor_ingreso` ASC) VISIBLE,
  CONSTRAINT `fk_PARQUE_NATURAL_CAR1`
    FOREIGN KEY (`CAR_id_CAR`)
    REFERENCES `parquesnaturalesdb`.`CAR` (`nit_CAR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARQUE_NATURAL_ESPECIES1`
    FOREIGN KEY (`ESPECIES_id_num_especies`)
    REFERENCES `parquesnaturalesdb`.`ESPECIES` (`id_num_especies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARQUE_NATURAL_DECRETO1`
    FOREIGN KEY (`DECRETO_num_decreto`)
    REFERENCES `parquesnaturalesdb`.`DECRETO` (`num_decreto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARQUE_NATURAL_VALOR_INGRESO1`
    FOREIGN KEY (`VALOR_INGRESO_id_valor_ingreso`)
    REFERENCES `parquesnaturalesdb`.`VALOR_INGRESO` (`id_valor_ingreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`VISITANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`VISITANTE` (
  `id_visitante` INT NOT NULL AUTO_INCREMENT,
  `fecha_nacimiento_visitante` DATE NOT NULL,
  `genero_visitante` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_visitante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`ACTIVIDAD_ILICITA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`ACTIVIDAD_ILICITA` (
  `id_actividad_ilicita` INT NOT NULL,
  `asunto_actividad_ilicita` VARCHAR(45) NOT NULL,
  `descripcion_actividad_ilicita` VARCHAR(45) NULL,
  `fecha_actividad_ilicita` DATE NOT NULL,
  `PARQUE_NATURAL_id_parque` INT NOT NULL,
  PRIMARY KEY (`id_actividad_ilicita`),
  INDEX `fk_ACTIVIDAD_ILICITA_PARQUE_NATURAL1_idx` (`PARQUE_NATURAL_id_parque` ASC) VISIBLE,
  CONSTRAINT `fk_ACTIVIDAD_ILICITA_PARQUE_NATURAL1`
    FOREIGN KEY (`PARQUE_NATURAL_id_parque`)
    REFERENCES `parquesnaturalesdb`.`PARQUE_NATURAL` (`id_parque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`TIPO_SERVICIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`TIPO_SERVICIO` (
  `id_tipo_servicio` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_servicio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_servicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`CATEGORIA_SERVICIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`CATEGORIA_SERVICIO` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(60) NOT NULL,
  `TIPO_SERVICIO_id_tipo_servicio` INT NOT NULL,
  PRIMARY KEY (`id_categoria`),
  INDEX `fk_CATEGORIA_SERVICIO_TIPO_SERVICIO1_idx` (`TIPO_SERVICIO_id_tipo_servicio` ASC) VISIBLE,
  CONSTRAINT `fk_CATEGORIA_SERVICIO_TIPO_SERVICIO1`
    FOREIGN KEY (`TIPO_SERVICIO_id_tipo_servicio`)
    REFERENCES `parquesnaturalesdb`.`TIPO_SERVICIO` (`id_tipo_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`SERVICIO_HOSPEDAJE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`SERVICIO_HOSPEDAJE` (
  `id_servicio` INT NOT NULL AUTO_INCREMENT,
  `nombre_servicio` VARCHAR(45) NOT NULL,
  `descripcion servicio` VARCHAR(45) NULL,
  `estado_servicio` TINYINT NOT NULL DEFAULT 1,
  `capacidad` INT NOT NULL,
  `valor_servicio` INT NOT NULL,
  `PARQUE_NATURAL_id_parque` INT NOT NULL,
  `CATEGORIA_SERVICIO_id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_servicio`),
  INDEX `fk_SERVICIO_ALOJAMIENTO_PARQUE_NATURAL1_idx` (`PARQUE_NATURAL_id_parque` ASC) VISIBLE,
  INDEX `fk_SERVICIO_ALOJAMIENTO_CATEGORIA_SERVICIO1_idx` (`CATEGORIA_SERVICIO_id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_SERVICIO_ALOJAMIENTO_PARQUE_NATURAL1`
    FOREIGN KEY (`PARQUE_NATURAL_id_parque`)
    REFERENCES `parquesnaturalesdb`.`PARQUE_NATURAL` (`id_parque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERVICIO_ALOJAMIENTO_CATEGORIA_SERVICIO1`
    FOREIGN KEY (`CATEGORIA_SERVICIO_id_categoria`)
    REFERENCES `parquesnaturalesdb`.`CATEGORIA_SERVICIO` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`ACTIVIDAD_ECOTURISTICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`ACTIVIDAD_ECOTURISTICA` (
  `id_actividad_ecoturistica` INT NOT NULL AUTO_INCREMENT,
  `nombre_actividad_ecoturistica` VARCHAR(45) NOT NULL,
  `estado_actividad_ecoturistica` TINYINT NOT NULL DEFAULT 1,
  `descripcion_actividad_ecoturistica` VARCHAR(256) NULL,
  `PARQUE_NATURAL_id_parque` INT NOT NULL,
  PRIMARY KEY (`id_actividad_ecoturistica`),
  INDEX `fk_ACTIVIDAD_ECOTURISTICA_PARQUE_NATURAL1_idx` (`PARQUE_NATURAL_id_parque` ASC) VISIBLE,
  CONSTRAINT `fk_ACTIVIDAD_ECOTURISTICA_PARQUE_NATURAL1`
    FOREIGN KEY (`PARQUE_NATURAL_id_parque`)
    REFERENCES `parquesnaturalesdb`.`PARQUE_NATURAL` (`id_parque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`INGRESO_VISITANTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`INGRESO_VISITANTES` (
  `PARQUE_NATURAL_id_parque` INT NOT NULL,
  `VISITANTE_id_visitante` INT NOT NULL,
  `fecha_ingreso` DATETIME NOT NULL,
  PRIMARY KEY (`PARQUE_NATURAL_id_parque`, `VISITANTE_id_visitante`),
  INDEX `fk_PARQUE_NATURAL_has_VISITANTE_VISITANTE1_idx` (`VISITANTE_id_visitante` ASC) VISIBLE,
  INDEX `fk_PARQUE_NATURAL_has_VISITANTE_PARQUE_NATURAL1_idx` (`PARQUE_NATURAL_id_parque` ASC) VISIBLE,
  CONSTRAINT `fk_PARQUE_NATURAL_has_VISITANTE_PARQUE_NATURAL1`
    FOREIGN KEY (`PARQUE_NATURAL_id_parque`)
    REFERENCES `parquesnaturalesdb`.`PARQUE_NATURAL` (`id_parque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARQUE_NATURAL_has_VISITANTE_VISITANTE1`
    FOREIGN KEY (`VISITANTE_id_visitante`)
    REFERENCES `parquesnaturalesdb`.`VISITANTE` (`id_visitante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`SOLICITANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`SOLICITANTE` (
  `id_solicitante` BIGINT NOT NULL,
  `nombre solicitante` VARCHAR(100) NOT NULL,
  `email_solicitante` VARCHAR(100) NOT NULL,
  `fecha_nacimiento_solicitante` DATE NOT NULL,
  `genero_solicitante` VARCHAR(9) NOT NULL,
  `telefono_solicitante` BIGINT NOT NULL,
  PRIMARY KEY (`id_solicitante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`ESTADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`ESTADO` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`SOLICITUD_RESERVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`SOLICITUD_RESERVA` (
  `SERVICIO_id_servicio` INT NOT NULL,
  `SOLICITANTE_id_solicitante` BIGINT NOT NULL,
  `numero_acompañantes` INT NULL,
  `inicio_reserva` DATETIME NOT NULL,
  `fin_reserva` DATETIME NOT NULL,
  `adelanto_reserva` TINYINT NOT NULL DEFAULT 0,
  `ESTADO_id_estado` INT NOT NULL,
  INDEX `fk_SOLICITUD_RESERVA_SERVICIO1_idx` (`SERVICIO_id_servicio` ASC) VISIBLE,
  INDEX `fk_SOLICITUD_RESERVA_SOLICITANTE1_idx` (`SOLICITANTE_id_solicitante` ASC) VISIBLE,
  INDEX `fk_SOLICITUD_RESERVA_ESTADO1_idx` (`ESTADO_id_estado` ASC) VISIBLE,
  CONSTRAINT `fk_SOLICITUD_RESERVA_SERVICIO1`
    FOREIGN KEY (`SERVICIO_id_servicio`)
    REFERENCES `parquesnaturalesdb`.`SERVICIO_HOSPEDAJE` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SOLICITUD_RESERVA_SOLICITANTE1`
    FOREIGN KEY (`SOLICITANTE_id_solicitante`)
    REFERENCES `parquesnaturalesdb`.`SOLICITANTE` (`id_solicitante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SOLICITUD_RESERVA_ESTADO1`
    FOREIGN KEY (`ESTADO_id_estado`)
    REFERENCES `parquesnaturalesdb`.`ESTADO` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`TIPO_PERSONAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`TIPO_PERSONAL` (
  `id_tipo_personal` INT NOT NULL AUTO_INCREMENT,
  `tipo_personal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_personal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`PERSONAL_PARQUE_NATURAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`PERSONAL_PARQUE_NATURAL` (
  `PARQUE_NATURAL_id_parque` INT NOT NULL,
  `TIPO_PERSONAL_id_tipo_personal` INT NOT NULL,
  `sueldo` INT NOT NULL,
  `CARGO_id_cargo` INT NOT NULL,
  `PERSONA_id_persona` BIGINT NOT NULL,
  PRIMARY KEY (`PARQUE_NATURAL_id_parque`),
  INDEX `fk_PARQUE_NATURAL_has_PERSONA_PARQUE_NATURAL1_idx` (`PARQUE_NATURAL_id_parque` ASC) VISIBLE,
  INDEX `fk_PERSONAL_PARQUE_NATURAL_TIPO_PERSONAL1_idx` (`TIPO_PERSONAL_id_tipo_personal` ASC) VISIBLE,
  INDEX `fk_PERSONAL_PARQUE_NATURAL_CARGO1_idx` (`CARGO_id_cargo` ASC) VISIBLE,
  INDEX `fk_PERSONAL_PARQUE_NATURAL_PERSONA1_idx` (`PERSONA_id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_PARQUE_NATURAL_has_PERSONA_PARQUE_NATURAL1`
    FOREIGN KEY (`PARQUE_NATURAL_id_parque`)
    REFERENCES `parquesnaturalesdb`.`PARQUE_NATURAL` (`id_parque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERSONAL_PARQUE_NATURAL_TIPO_PERSONAL1`
    FOREIGN KEY (`TIPO_PERSONAL_id_tipo_personal`)
    REFERENCES `parquesnaturalesdb`.`TIPO_PERSONAL` (`id_tipo_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERSONAL_PARQUE_NATURAL_CARGO1`
    FOREIGN KEY (`CARGO_id_cargo`)
    REFERENCES `parquesnaturalesdb`.`CARGO` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERSONAL_PARQUE_NATURAL_PERSONA1`
    FOREIGN KEY (`PERSONA_id_persona`)
    REFERENCES `parquesnaturalesdb`.`PERSONA` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquesnaturalesdb`.`USUARIOS_CAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquesnaturalesdb`.`USUARIOS_CAR` (
  `id_usuario_car` INT NOT NULL AUTO_INCREMENT,
  `PERSONA_id_persona` BIGINT NOT NULL,
  `CAR_nit_CAR` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_usuario_car`),
  INDEX `fk_USUARIOS_CAR_PERSONA1_idx` (`PERSONA_id_persona` ASC) VISIBLE,
  INDEX `fk_USUARIOS_CAR_CAR1_idx` (`CAR_nit_CAR` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIOS_CAR_PERSONA1`
    FOREIGN KEY (`PERSONA_id_persona`)
    REFERENCES `parquesnaturalesdb`.`PERSONA` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOS_CAR_CAR1`
    FOREIGN KEY (`CAR_nit_CAR`)
    REFERENCES `parquesnaturalesdb`.`CAR` (`nit_CAR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
